{"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy/issues/60/comments/3387632.json"}, "html": {"href": "#!/osrf/cloudsim-legacy/issues/60#comment-3387632"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy/issues/60.json"}}, "type": "issue", "id": 60, "repository": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy.json"}, "html": {"href": "#!/osrf/cloudsim-legacy"}, "avatar": {"href": "data/bytebucket.org/ravatar/{e799e7f6-0caa-464a-97f8-8605a37ebfb1}ts=python"}}, "type": "repository", "name": "cloudsim-legacy", "full_name": "osrf/cloudsim-legacy", "uuid": "{e799e7f6-0caa-464a-97f8-8605a37ebfb1}"}, "title": "Console doesn't display constellation anymore"}, "content": {"raw": "The CloudSim machine's database is corrupt or it does not contain any information about the constellation cxe378f80a. \n\nPlease verify that constellation cxe378f80a was created from that CloudSim instance (54.242.249.62). This should be the case, since things were working before.\n\nThe next thing to do is to log in the CloudSim instance. You will need the ssh keys available via the \"ssh key download\" link at the top right corner of CloudSim (you must be logged in with admin privileges).\n\nOnce in the CloudSim instance, use the root account (sudo su) to look for the following directory:\n\n\n```\n#!python\n\n/var/www-cloudsim-auth/machines/cxe378f80a\n```\n\nYou should be able to find the keys to your machines there.\n\nThen, look for\n\n\n```\n#!python\n\n/tmp/cloudsimd.log\n```\n\nThis could give a clue to what may have happened. Can you send the content?\n\nYou can also stop and start the daemon by running:\n\n\n```\n#!python\n\nsudo stop cloudsimd\n\nand\n\nsudo start cloudsimd\n\n```\n\nIts important to note that you don't need CloudSim to use the constellation machines. However, what you are experiencing is not normal and we should find the cause for this problem. Next steps could involve adding an osrf user to the admin list.\n", "markup": "markdown", "html": "<p>The CloudSim machine's database is corrupt or it does not contain any information about the constellation cxe378f80a. </p>\n<p>Please verify that constellation cxe378f80a was created from that CloudSim instance (54.242.249.62). This should be the case, since things were working before.</p>\n<p>The next thing to do is to log in the CloudSim instance. You will need the ssh keys available via the \"ssh key download\" link at the top right corner of CloudSim (you must be logged in with admin privileges).</p>\n<p>Once in the CloudSim instance, use the root account (sudo su) to look for the following directory:</p>\n<div class=\"codehilite language-python\"><pre><span></span><span class=\"o\">/</span><span class=\"n\">var</span><span class=\"o\">/</span><span class=\"n\">www</span><span class=\"o\">-</span><span class=\"n\">cloudsim</span><span class=\"o\">-</span><span class=\"n\">auth</span><span class=\"o\">/</span><span class=\"n\">machines</span><span class=\"o\">/</span><span class=\"n\">cxe378f80a</span>\n</pre></div>\n\n\n<p>You should be able to find the keys to your machines there.</p>\n<p>Then, look for</p>\n<div class=\"codehilite language-python\"><pre><span></span><span class=\"o\">/</span><span class=\"n\">tmp</span><span class=\"o\">/</span><span class=\"n\">cloudsimd</span><span class=\"o\">.</span><span class=\"n\">log</span>\n</pre></div>\n\n\n<p>This could give a clue to what may have happened. Can you send the content?</p>\n<p>You can also stop and start the daemon by running:</p>\n<div class=\"codehilite language-python\"><pre><span></span><span class=\"n\">sudo</span> <span class=\"n\">stop</span> <span class=\"n\">cloudsimd</span>\n\n<span class=\"ow\">and</span>\n\n<span class=\"n\">sudo</span> <span class=\"n\">start</span> <span class=\"n\">cloudsimd</span>\n</pre></div>\n\n\n<p>Its important to note that you don't need CloudSim to use the constellation machines. However, what you are experiencing is not normal and we should find the cause for this problem. Next steps could involve adding an osrf user to the admin list.</p>", "type": "rendered"}, "created_on": "2013-03-12T18:23:43.824698+00:00", "user": {"display_name": "Hugo Boyer", "uuid": "{3d87874e-7099-4981-b04f-57f0272faa7d}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D"}, "html": {"href": "https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/21198da8539b599e3633017f5f5f8150d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsHB-6.png"}}, "nickname": "hugomatic", "type": "user", "account_id": "557058:869c02bb-b246-4cdc-9db3-0064e8add185"}, "updated_on": null, "type": "issue_comment", "id": 3387632}