{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-auth.json"}, "html": {"href": "#!/osrf/cloudsim-auth"}, "avatar": {"href": "data/bytebucket.org/ravatar/{fcbe065d-e7d7-4c83-9ca6-5e91154a993c}ts=default"}}, "type": "repository", "name": "cloudsim-auth", "full_name": "osrf/cloudsim-auth", "uuid": "{fcbe065d-e7d7-4c83-9ca6-5e91154a993c}"}, "links": {"attachments": {"href": "data/repositories/osrf/cloudsim-auth/issues/8/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/cloudsim-auth/issues/8.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/cloudsim-auth/issues/8/watch"}, "comments": {"href": "data/repositories/osrf/cloudsim-auth/issues/8/comments_page=1.json"}, "html": {"href": "#!/osrf/cloudsim-auth/issues/8/if-you-are-on-a-subpage-when-you-try-to"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/cloudsim-auth/issues/8/vote"}}, "reporter": {"display_name": "Tully Foote", "uuid": "{3d90dbd4-b845-466f-b5bd-068566f7ff50}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d90dbd4-b845-466f-b5bd-068566f7ff50%7D"}, "html": {"href": "https://bitbucket.org/%7B3d90dbd4-b845-466f-b5bd-068566f7ff50%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/3bc6528f8fe1fef6b6ecc7312ee0cf04d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsTF-2.png"}}, "nickname": "Tully Foote", "type": "user", "account_id": "557058:e2bf789f-2138-4a4e-ba39-3d618078e20b"}, "title": "If you are on a subpage when you try to login you get an error about an invalid callback url", "component": null, "votes": 0, "watches": 1, "content": {"raw": "It appears that auth0 is asked to give a callback at the current url, instead of the standard url of cloudsim.io\r\n\r\nTo reproduce: \r\n\r\nGo to https://cloudsim.io/dashboard or any not bare domain name and try to login. \r\n\r\n![auth0cb_issue.png](data/bitbucket.org/repo/Rknzjp/images/726339048-auth0cb_issue.png)", "markup": "markdown", "html": "<p>It appears that auth0 is asked to give a callback at the current url, instead of the standard url of cloudsim.io</p>\n<p>To reproduce: </p>\n<p>Go to <a href=\"https://cloudsim.io/dashboard\" rel=\"nofollow\" class=\"ap-connect-link\">https://cloudsim.io/dashboard</a> or any not bare domain name and try to login. </p>\n<p><img alt=\"auth0cb_issue.png\" src=\"data/bitbucket.org/repo/Rknzjp/images/726339048-auth0cb_issue.png\" /></p>", "type": "rendered"}, "assignee": null, "state": "new", "version": null, "edited_on": null, "created_on": "2016-11-30T08:37:10.232595+00:00", "milestone": null, "updated_on": "2016-11-30T08:50:27.961387+00:00", "type": "issue", "id": 8}