{"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy/issues/49/comments/3311710.json"}, "html": {"href": "#!/osrf/cloudsim-legacy/issues/49#comment-3311710"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy/issues/49.json"}}, "type": "issue", "id": 49, "repository": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy.json"}, "html": {"href": "#!/osrf/cloudsim-legacy"}, "avatar": {"href": "data/bytebucket.org/ravatar/{e799e7f6-0caa-464a-97f8-8605a37ebfb1}ts=python"}}, "type": "repository", "name": "cloudsim-legacy", "full_name": "osrf/cloudsim-legacy", "uuid": "{e799e7f6-0caa-464a-97f8-8605a37ebfb1}"}, "title": "ROS Network is not working properly from the field computer to the local computer"}, "content": {"raw": "The only node that runs in the local OCU is our node. We are not running our node before setting the environment (ros.sh) so, the ROS_IP and GAZEBO_IP are setup beforehand.\n\nI made more checks and I am wondering: all the nodes running on the field computer report that they can be contacted via the simulator ip:\n\nFor example, the node C21 runs on the field computer and the following is done on the field computer:\n\n```\n#!script\n\nubuntu@ip-10-0-0-52:~/integrator/robil/C0_Scripts$ rosnode info /C21_VisionAndLidar \n--------------------------------------------------------------------------------\nNode [/C21_VisionAndLidar]\nPublications: \n * /C21/C22 [C21_VisionAndLidar/C21_C22]\n * /C21/right_camera/image [sensor_msgs/Image]\n * /rosout [rosgraph_msgs/Log]\n * /C21/left_camera/image [sensor_msgs/Image]\n\nSubscriptions: \n * /multisense_sl/camera/left/image_raw [sensor_msgs/Image]\n * /tf [tf/tfMessage]\n * /multisense_sl/camera/points2 [sensor_msgs/PointCloud2]\n * /multisense_sl/camera/right/image_raw [sensor_msgs/Image]\n * /clock [rosgraph_msgs/Clock]\n\nServices: \n * /C21/Panorama\n * /C21_VisionAndLidar/tf_frames\n * /C21_VisionAndLidar/set_logger_level\n * /C21/Pic\n * /C21_VisionAndLidar/get_loggers\n * /C21\n\n\ncontacting node http://10.0.0.52:34888/ ...\nPid: 1949\nConnections:\n * topic: /rosout\n    * to: /rosout\n    * direction: outbound\n    * transport: TCPROS\n * topic: /C21/C22\n    * to: /c22_groundReconition_and_mapping\n    * direction: outbound\n    * transport: TCPROS\n * topic: /C21/C22\n    * to: /C25_GlobalPosition\n    * direction: outbound\n    * transport: TCPROS\n * topic: /clock\n    * to: /gazebo (http://10.0.0.51:35307/)\n    * direction: inbound\n    * transport: TCPROS\n * topic: /multisense_sl/camera/left/image_raw\n    * to: /gazebo (http://10.0.0.51:35307/)\n    * direction: inbound\n    * transport: TCPROS\n * topic: /multisense_sl/camera/right/image_raw\n    * to: /gazebo (http://10.0.0.51:35307/)\n    * direction: inbound\n    * transport: TCPROS\n * topic: /multisense_sl/camera/points2\n    * to: /multisense_sl/camera/stereo_proc (http://10.0.0.51:45902/)\n    * direction: inbound\n    * transport: TCPROS\n * topic: /tf\n    * to: /multisense_sl_robot_state_publisher (http://10.0.0.51:46307/)\n    * direction: inbound\n    * transport: TCPROS\n * topic: /tf\n    * to: /atlas_robot_state_publisher (http://10.0.0.51:56306/)\n    * direction: inbound\n    * transport: TCPROS\n\n```\nBut I guess that it is normal since the master is 10.0.0.51\n\nNote that when I am running the node at the local OCU, it prints the following:\n(Note the **localhost**)\n\n```\n#!script\n\nmichele@darpaws5:~/trio/router_cxe378f80a$ roslaunch C11_OperatorControl C11.launch \n... logging to /home/michele/.ros/log/b55b5af2-8556-11e2-bd49-129f0dc065c6/roslaunch-darpaws5-3455.log\nChecking log directory for disk usage. This may take awhile.\nPress Ctrl-C to interrupt\nDone checking log file disk usage. Usage is <1GB.\n\nstarted roslaunch server http://localhost:45983/\n\nSUMMARY\n========\n\nPARAMETERS\n * /rosdistro\n * /rosversion\n\nNODES\n  /\n    c11 (C11_OperatorControl/c11)\n\nROS_MASTER_URI=http://10.0.0.51:11311\n\ncore service [/rosout] found\nException AttributeError: AttributeError(\"'_DummyThread' object has no attribute '_Thread__block'\",) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored\nprocess[c11-1]: started with pid [3466]\n\n```\nActually, I run different nodes on the local OCU and I get the same result consistently: the nodes running locally are not accessible from the field and simulator computers.\n\nFor fun, I run the OCU local node on the field computer and it displays the following:\n(Note the server is not local host here)\n```\n#!script\n\nubuntu@ip-10-0-0-52:~/integrator/robil/C0_Scripts$ roslaunch C11_OperatorControl C11.launch \n... logging to /home/ubuntu/.ros/log/b55b5af2-8556-11e2-bd49-129f0dc065c6/roslaunch-ip-10-0-0-52-2084.log\nChecking log directory for disk usage. This may take awhile.\nPress Ctrl-C to interrupt\nDone checking log file disk usage. Usage is <1GB.\n\nstarted roslaunch server http://10.0.0.52:40430/\n\nSUMMARY\n========\n\nPARAMETERS\n * /rosdistro\n * /rosversion\n\nNODES\n  /\n    c11 (C11_OperatorControl/c11)\n\nROS_MASTER_URI=http://10.0.0.51:11311\n\ncore service [/rosout] found\nException AttributeError: AttributeError(\"'_DummyThread' object has no attribute '_Thread__block'\",) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored\nprocess[c11-1]: started with pid [2095]\n\n```", "markup": "markdown", "html": "<p>The only node that runs in the local OCU is our node. We are not running our node before setting the environment (ros.sh) so, the ROS_IP and GAZEBO_IP are setup beforehand.</p>\n<p>I made more checks and I am wondering: all the nodes running on the field computer report that they can be contacted via the simulator ip:</p>\n<p>For example, the node C21 runs on the field computer and the following is done on the field computer:</p>\n<div class=\"codehilite language-script\"><pre><span></span>ubuntu@ip-10-0-0-52:~/integrator/robil/C0_Scripts$ rosnode info /C21_VisionAndLidar \n--------------------------------------------------------------------------------\nNode [/C21_VisionAndLidar]\nPublications: \n * /C21/C22 [C21_VisionAndLidar/C21_C22]\n * /C21/right_camera/image [sensor_msgs/Image]\n * /rosout [rosgraph_msgs/Log]\n * /C21/left_camera/image [sensor_msgs/Image]\n\nSubscriptions: \n * /multisense_sl/camera/left/image_raw [sensor_msgs/Image]\n * /tf [tf/tfMessage]\n * /multisense_sl/camera/points2 [sensor_msgs/PointCloud2]\n * /multisense_sl/camera/right/image_raw [sensor_msgs/Image]\n * /clock [rosgraph_msgs/Clock]\n\nServices: \n * /C21/Panorama\n * /C21_VisionAndLidar/tf_frames\n * /C21_VisionAndLidar/set_logger_level\n * /C21/Pic\n * /C21_VisionAndLidar/get_loggers\n * /C21\n\n\ncontacting node http://10.0.0.52:34888/ ...\nPid: 1949\nConnections:\n * topic: /rosout\n    * to: /rosout\n    * direction: outbound\n    * transport: TCPROS\n * topic: /C21/C22\n    * to: /c22_groundReconition_and_mapping\n    * direction: outbound\n    * transport: TCPROS\n * topic: /C21/C22\n    * to: /C25_GlobalPosition\n    * direction: outbound\n    * transport: TCPROS\n * topic: /clock\n    * to: /gazebo (http://10.0.0.51:35307/)\n    * direction: inbound\n    * transport: TCPROS\n * topic: /multisense_sl/camera/left/image_raw\n    * to: /gazebo (http://10.0.0.51:35307/)\n    * direction: inbound\n    * transport: TCPROS\n * topic: /multisense_sl/camera/right/image_raw\n    * to: /gazebo (http://10.0.0.51:35307/)\n    * direction: inbound\n    * transport: TCPROS\n * topic: /multisense_sl/camera/points2\n    * to: /multisense_sl/camera/stereo_proc (http://10.0.0.51:45902/)\n    * direction: inbound\n    * transport: TCPROS\n * topic: /tf\n    * to: /multisense_sl_robot_state_publisher (http://10.0.0.51:46307/)\n    * direction: inbound\n    * transport: TCPROS\n * topic: /tf\n    * to: /atlas_robot_state_publisher (http://10.0.0.51:56306/)\n    * direction: inbound\n    * transport: TCPROS\n</pre></div>\n\n\n<p>But I guess that it is normal since the master is 10.0.0.51</p>\n<p>Note that when I am running the node at the local OCU, it prints the following:\n(Note the <strong>localhost</strong>)</p>\n<div class=\"codehilite language-script\"><pre><span></span>michele@darpaws5:~/trio/router_cxe378f80a$ roslaunch C11_OperatorControl C11.launch \n... logging to /home/michele/.ros/log/b55b5af2-8556-11e2-bd49-129f0dc065c6/roslaunch-darpaws5-3455.log\nChecking log directory for disk usage. This may take awhile.\nPress Ctrl-C to interrupt\nDone checking log file disk usage. Usage is &lt;1GB.\n\nstarted roslaunch server http://localhost:45983/\n\nSUMMARY\n========\n\nPARAMETERS\n * /rosdistro\n * /rosversion\n\nNODES\n  /\n    c11 (C11_OperatorControl/c11)\n\nROS_MASTER_URI=http://10.0.0.51:11311\n\ncore service [/rosout] found\nException AttributeError: AttributeError(&quot;&#39;_DummyThread&#39; object has no attribute &#39;_Thread__block&#39;&quot;,) in &lt;module &#39;threading&#39; from &#39;/usr/lib/python2.7/threading.pyc&#39;&gt; ignored\nprocess[c11-1]: started with pid [3466]\n</pre></div>\n\n\n<p>Actually, I run different nodes on the local OCU and I get the same result consistently: the nodes running locally are not accessible from the field and simulator computers.</p>\n<p>For fun, I run the OCU local node on the field computer and it displays the following:\n(Note the server is not local host here)</p>\n<div class=\"codehilite language-script\"><pre><span></span>ubuntu@ip-10-0-0-52:~/integrator/robil/C0_Scripts$ roslaunch C11_OperatorControl C11.launch \n... logging to /home/ubuntu/.ros/log/b55b5af2-8556-11e2-bd49-129f0dc065c6/roslaunch-ip-10-0-0-52-2084.log\nChecking log directory for disk usage. This may take awhile.\nPress Ctrl-C to interrupt\nDone checking log file disk usage. Usage is &lt;1GB.\n\nstarted roslaunch server http://10.0.0.52:40430/\n\nSUMMARY\n========\n\nPARAMETERS\n * /rosdistro\n * /rosversion\n\nNODES\n  /\n    c11 (C11_OperatorControl/c11)\n\nROS_MASTER_URI=http://10.0.0.51:11311\n\ncore service [/rosout] found\nException AttributeError: AttributeError(&quot;&#39;_DummyThread&#39; object has no attribute &#39;_Thread__block&#39;&quot;,) in &lt;module &#39;threading&#39; from &#39;/usr/lib/python2.7/threading.pyc&#39;&gt; ignored\nprocess[c11-1]: started with pid [2095]\n</pre></div>", "type": "rendered"}, "created_on": "2013-03-05T06:01:07.105742+00:00", "user": {"display_name": "michele hallak", "uuid": "{f8cca72b-2f8a-4372-bcb5-10ea801a3fe9}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bf8cca72b-2f8a-4372-bcb5-10ea801a3fe9%7D"}, "html": {"href": "https://bitbucket.org/%7Bf8cca72b-2f8a-4372-bcb5-10ea801a3fe9%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/d10108e88396c34c2d474c28bba19974d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsMH-1.png"}}, "nickname": "mhallak", "type": "user", "account_id": "557058:643e25c4-f0cd-4e12-8c67-7a038a7e7e40"}, "updated_on": "2013-03-05T06:07:48.340135+00:00", "type": "issue_comment", "id": 3311710}