{"links": {"self": {"href": "data/repositories/osrf/cloudsim-auth/issues/8/comments/32545567.json"}, "html": {"href": "#!/osrf/cloudsim-auth/issues/8#comment-32545567"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-auth/issues/8.json"}}, "type": "issue", "id": 8, "repository": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-auth.json"}, "html": {"href": "#!/osrf/cloudsim-auth"}, "avatar": {"href": "data/bytebucket.org/ravatar/{fcbe065d-e7d7-4c83-9ca6-5e91154a993c}ts=default"}}, "type": "repository", "name": "cloudsim-auth", "full_name": "osrf/cloudsim-auth", "uuid": "{fcbe065d-e7d7-4c83-9ca6-5e91154a993c}"}, "title": "If you are on a subpage when you try to login you get an error about an invalid callback url"}, "content": {"raw": null, "markup": "markdown", "html": "", "type": "rendered"}, "created_on": "2016-11-30T08:37:32.585471+00:00", "user": {"display_name": "Tully Foote", "uuid": "{3d90dbd4-b845-466f-b5bd-068566f7ff50}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d90dbd4-b845-466f-b5bd-068566f7ff50%7D"}, "html": {"href": "https://bitbucket.org/%7B3d90dbd4-b845-466f-b5bd-068566f7ff50%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/3bc6528f8fe1fef6b6ecc7312ee0cf04d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsTF-2.png"}}, "nickname": "Tully Foote", "type": "user", "account_id": "557058:e2bf789f-2138-4a4e-ba39-3d618078e20b"}, "updated_on": null, "type": "issue_comment", "id": 32545567}