{"priority": "major", "kind": "enhancement", "repository": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy.json"}, "html": {"href": "#!/osrf/cloudsim-legacy"}, "avatar": {"href": "data/bytebucket.org/ravatar/{e799e7f6-0caa-464a-97f8-8605a37ebfb1}ts=python"}}, "type": "repository", "name": "cloudsim-legacy", "full_name": "osrf/cloudsim-legacy", "uuid": "{e799e7f6-0caa-464a-97f8-8605a37ebfb1}"}, "links": {"attachments": {"href": "data/repositories/osrf/cloudsim-legacy/issues/18/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/cloudsim-legacy/issues/18.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/cloudsim-legacy/issues/18/watch"}, "comments": {"href": "data/repositories/osrf/cloudsim-legacy/issues/18/comments_page=1.json"}, "html": {"href": "#!/osrf/cloudsim-legacy/issues/18/automatic-termination-in-case-of-failed"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/cloudsim-legacy/issues/18/vote"}}, "reporter": {"display_name": "Hugo Boyer", "uuid": "{3d87874e-7099-4981-b04f-57f0272faa7d}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D"}, "html": {"href": "https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/21198da8539b599e3633017f5f5f8150d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsHB-6.png"}}, "nickname": "hugomatic", "type": "user", "account_id": "557058:869c02bb-b246-4cdc-9db3-0064e8add185"}, "title": "Automatic termination in case of failed launches", "component": null, "votes": 0, "watches": 0, "content": {"raw": "When a constellation fails to launch, some AWS resources are not released automatically.\r\n\r\nThis can happen for a variety of reasons:\r\n* instance capacity limits at AWS\r\n* instance limits in the account (for machine types)\r\n* other limits (nb of VPCs, elastic Ips, ...)\r\n\r\nRunning the terminate automatically works, but it publishes messages that hide the problem. A \"silent\" terminate should be implemented, or error messages could be placed somewhere.", "markup": "markdown", "html": "<p>When a constellation fails to launch, some AWS resources are not released automatically.</p>\n<p>This can happen for a variety of reasons:\n<em> instance capacity limits at AWS\n</em> instance limits in the account (for machine types)\n* other limits (nb of VPCs, elastic Ips, ...)</p>\n<p>Running the terminate automatically works, but it publishes messages that hide the problem. A \"silent\" terminate should be implemented, or error messages could be placed somewhere.</p>", "type": "rendered"}, "assignee": null, "state": "resolved", "version": null, "edited_on": null, "created_on": "2013-02-04T18:49:18.315144+00:00", "milestone": null, "updated_on": "2013-03-13T16:10:00.102329+00:00", "type": "issue", "id": 18}